x<-read.csv2("hpc.txt")
x<-subset(x,Date %in% c("1/2/2007","2/2/2007"))
x$Global_active_power<- as.numeric(x$Global_active_power)/1000
datetime <- strptime(paste(x$Date, x$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
x$Sub_metering_1<- as.numeric(x$Sub_metering_1)
x$Sub_metering_2<- as.numeric(x$Sub_metering_2)
x$Sub_metering_3<- as.numeric(x$Sub_metering_3)
png("plot4.png",width = 480, height = 480)
par(mfcol=c(2,2))
plot(datetime,x$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
plot(datetime,x$Sub_metering_1,type = "l",xlab = "",ylab = "Energy sub metering",col= "black")
lines(datetime,x$Sub_metering_2 ,type = "l",col ="red")
lines(datetime,x$Sub_metering_3 ,type = "l",col ="blue")
legend("topright",legend = c("submetering1","submeterting2","submetering2"),col = c("black","red","blue"),lty = 1,lwd = 2.5 )
plot(datetime,x$Voltage,type="l",xlab = "datetime" , ylab = "voltage")
plot(datetime,x$Global_reactive_power,type = "l",xlab = "datetime",ylab = "Global_Reactive_power")
dev.off()
